name: Update Tag Network JSON

on:
  schedule:
    - cron: "0 2 * * *" # Every day at 2 AM UTC
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run tag network script
        run: python github_tags_to_json.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated update of tag_network.json
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          branch: main
          token: ${{ secrets.GH_PAT }}
