name: Update Tag Network JSON

on:
  schedule:
    - cron: "0 2 * * *"  # Runs daily at 2 AM UTC
  workflow_dispatch:     # Allows manual trigger from GitHub UI

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Add other dependencies here if your script requires them

      - name: Run Python script to update JSON
        run: |
          python github_tags_to_json.py

      - name: Commit and push updated JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add tag_network.json
          git diff --cached --quiet || (git commit -m "Automated update of tag_network.json" && git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/tjnolan319/network-visualization.git HEAD:main)
